title: Simao Chen (Alice)'s personal website
description: >- 
  This is my personal website hosted on GitHub Pages.
email: alicechen005 at gmail.com; sc4916 at nyu.edu
github_username:  simaoalicechen
# Build settings
theme: jekyll-theme-minimal
